name: FootswitchController
options:
  bundleIdPrefix: com.luckysama
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    DEVELOPMENT_TEAM: "N957X4L8PY"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Developer ID Application: Yoshiharu Sato (N957X4L8PY)"
    PROVISIONING_PROFILE_SPECIFIER: ""
targets:
  FootswitchController:
    type: application
    platform: macOS
    sources:
      - path: FootswitchController
    info:
      path: FootswitchController/Info.plist
      properties:
        CFBundleName: FootswitchController
        CFBundleDisplayName: Footswitch Controller
        CFBundleShortVersionString: "0.2.2"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright (c) 2026 Lucky Sama"
        NSAppleEventsUsageDescription: "フットスイッチからアプリにキー入力を送るために使用します。"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luckysama.footswitch-controller
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: FootswitchController/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: FootswitchController/FootswitchController.entitlements
